### ISSUE TITLE
OpenGL Material Preview Improvements

### ISSUE THREAD

**Issue by mifth** [bsavery/RenderManForBlender#124]
Hi.

Cycles has good material preview in Material Mode. It can preview shader colors and textures.
Here is example:

File: https://dl.dropboxusercontent.com/u/26887202/blender/temp_pr.blend

Image:
![_002](https://cloud.githubusercontent.com/assets/2251298/9498479/c20b6252-4c22-11e5-8c8a-d9ab5326b398.png)

Is it possible to add to PRMAN?

**Comment by bsavery** [comment]
Thanks.  The interactive preview with PRMan is meant to do something similar, and I think the advantages and disadvantages have been covered elsewhere.  Mainly that it's not using the blender window currently and we're able to update lights, camera, materials but not move geometry without restarting the interactive render.  However we get the fully lit/shaded result.

**Comment by mifth** [comment]
Wait, wait. This is blender's opengl part. Just open my blend file and check the left window.
Shader cooors and textures are displayed in 3d viewport.

The right window is just comparison for cycles renderer and the 3d material viewport.
Also, cycles material nodes to see what happens.

**Comment by bsavery** [comment]
Gotcha.  Yeah I'm not that great with opengl stuff.  It might not be too hard to implement doing material preview in the viewport.  I'm going to relabel this thread.  

Ideally someone who is really good with opengl could focus on this.

**Comment by bsavery** [comment]
The other issue is that it would be a ton of work to translate all the Bxdfs to opengl, but I'm sure something simple could be done.

**Comment by mifth** [comment]
Thanks for confirmation.
It's not a ton of work i think.
You have not so much shaders. Desney, skin, glass, susurf...
All you need is just to get input color/texture of a shader.

Also cycles is the python addon. You can check it in blender's scripts folder. They implemented it through the python addon too.

**Comment by mifth** [comment]
Cycles Addon is located here:
![_004](https://cloud.githubusercontent.com/assets/2251298/9516672/dc212326-4cb2-11e5-8d05-1f5abccaa78c.png)

You can just grab the code of the preview of colors and shaders in MaterialMode.

**Comment by bsavery** [comment]
Any chance you'd be willing to contribute that code with a pull request?  I can take a look but I'm a bit busy this week.

**Comment by Lightye** [comment]
It would be awsome with some real open-GL connections. However, if it is a bit too much to do at the moment, one suggestion could be the following. If possible, maybe try to just copy the colors of diffuse to the underlying Blender materials (that is already connected to lights), and maybe set "texture" display as default. It is quite a cheat, but if it is possible to copy the color temporarily it would at least "look" much better than boring grey. Otherwise, if there is someone who would like to do it properly, please just ignore this simple idea. Anyway, you are doing an awesome investment. Cheers!

**Comment by Lightye** [comment]
Sorry guys for the many posts. This idea has been popping back a few times, and after seeing a demo of Maya 2016 I think it might not be a good idea to go down the open-GL path. There are several reasons. The first is that I'm a WYSIWYG-guy. Second, translating everything between RenderMan and open-GL might be a waste of time. Third, maybe RenderMan will add native support for graphic cards (since there is research underway). So what I propose is something like this: http://sawe.asuscomm.com/published/renderman/blender/gui_proposals/20150903_interactive_with_wire_overlay_proposal.jpg. Sorry that I'm not a good programmer, however, I did open-GL in university level, and honestly, the capabilities are so limited who really want's it. I would maybe propose that we let the users use a limited sub-set of RenderMan if they want faster display. Just tell me to shut up if you think I'm totally lost here. However, this are my honest ideas, and since I'm a Photoshop guy I can try out ideas if you want, graphically. So they can be discussed I mean, pros and cons. Maybe it could be developed. Cheers!

**Comment by MWY3510** [comment]
Lightye,

I'm trying to understand what you are suggesting. What I think you're proposing is similar to the view-port rendering of cycles but with a wire-frame overlay. Let me know if I am mistaken or am missing something.

MWY3510

**Comment by Lightye** [comment]
You are on the spot.

**Comment by Lightye** [comment]
It does not necessarily hinder a separate open-GL thing, but honestly if I want open-GL I could use Cycles or Blender. Blah, sorry for the many posts. Maybe we should go another way than Maya and the other guys and innovate.

**Comment by Lightye** [comment]
In this video https://www.youtube.com/watch?v=5obEtnSBkBE they talk about converting stuff between different "renderers", and as an artist I just think it suck to need to convert. Why not use the right thing from the beginning, and downgrade or disable features if needed?

**Comment by bsavery** [comment]
^^^^ this.  I think it depends how much time you want to spend translating RIS pattern networks.  If just getting color and some basic lights into opengl is good enough, then that's simple.  However if you don't want to always be chasing converting more things to opengl, then the ultimate goal would be to be able to do everything in a "PRMan viewport" that would let you add geometry, and move and do everything you want.

**Comment by MWY3510** [comment]
I think a hybrid solution would be the best. 1) A basic openGL preview mode that has lighting and color information. 2) A PRMan viewport option that as bsavery says would show everything.

MWY3510

**Comment by bsavery** [comment]
Just to be clear the current IPR in PRMan has limitations now but of course will improve over time.

**Comment by Lightye** [comment]
So will the machines.

**Comment by Lightye** [comment]
Adding ability to disable camera rays on everything but selected could do a lot for those with a few cores only.

**Comment by MWY3510** [comment]
bsavery,

So as IPR improves should we look into integrating it into the viewport?

MWY3510

**Comment by Lightye** [comment]
Hey guys, I don't want to put pressure on you. In the end a hybrid where the user can choose one or two editors for interactive display would probably be rock solid. However, considering using open-GL a lot or spending time with that I just think is such a waste at the moment. Those who do lighting and materials want to see as closely as possible what the end result will be, not some "maybe it will look something like that". Animators could just use Blender default or Cycles, but lighters can use PRMan interactive. Great work with all that you do, prman is really a great renderer and the quality look amazing. Cheers!

**Comment by Lightye** [comment]
Maybe I can try to do a video demo to see what a hybrid with wireframe overlay could look like.

**Comment by MWY3510** [comment]
Lightye,

Sounds great, I still think that only the basic gl part of the hybrid is possible at the moment.

**Comment by Lightye** [comment]
That's fine. 

http://sawe.asuscomm.com/published/renderman/blender/gui_proposals/20150904_prman_for_blender_renderman_with_wire_overlay.mp4

**Comment by Lightye** [comment]
The Blender UI is flexible. Some kind of miniature interactive view plus basic open-GL or wire also look good. Core material and light setup need to work for lighters doing 8-12 h days. The constant "redrawing" in the face could be tiring to look at for a long time, or no? As a background miniature It could however be helpful or integrated in viewport. Just some ideas. Trash em if you don't like, or adjust and develop.  http://sawe.asuscomm.com/published/renderman/blender/gui_proposals/20150904_interactive_with_it_alternative.png

**Comment by Lightye** [comment]
Did some tests with Blender's current functions. To get an image of the render output as background just set the "Background Images" to Render Result. The image will however only update when it is redrawed. 
![render_as_background_almost_already_supported](https://cloud.githubusercontent.com/assets/14073317/9738199/bc588eca-564a-11e5-8212-242372ed4b39.png)

**Comment by bsavery** [comment]
<img width="1920" alt="screen shot 2016-01-31 at 6 55 55 pm" src="https://cloud.githubusercontent.com/assets/1892220/12707693/60f1fec6-c84c-11e5-8f76-de0c6380e01f.png">

Like this?

**Comment by MWY3510** [comment]
Great Brian. What did you do to get that result.

**Comment by bsavery** [comment]
Using the new "internal" display driver and then copy the render result to the background.  Just playing around with things.  It's still testing and need to see about getting the display driver working for ipr...

**Comment by MWY3510** [comment]
Great things will come from having IPR and the internal display driver working together.

**Comment by Lightye** [comment]
It is nice to see some progress in this area as well. Regarding the wire on IPR concept please consider that for example industrial designers, architects and traditional animators are used to seeing some guidelines (cross sections) on their sketches. Blender has some "optimal display" mode that will reduce those wire lines to only a few when using the subdiv modifier. It is already fairly easy to toggle the display of wireframe as well if a user would like to see IPR only. As a shader developer and lighter this is actually what you want to see (they basically want to check that the shader setup works for each part). If a shader/lighting artist can go through all the assets in a scene using some kind of "IPR selected only" and then finally batch render them all out together with some kind of ID/material-mask (or equivalent) to use in post it should be effective. Final (fine) tweaking can then be done in Post and not in Blender. Such a workflow idea could be pushed, optimized and finally presented. It should provide less waiting, more interactivity, and maximized control. Imagine doing this on a very high-end workstation and then sending the batch to a strong rendercow. A company/professional would need two strong multicore computers and one license (if the free can be used to setup the scene, and the commercial for the rendercow). Based on my experience, these are just some thoughts. Alternative workflows could work also.

**Comment by Lightye** [comment]
Other workflows could be if time allow re-rendering the tweaking could be done in Blender (using preview quality) and not in post using ID/material masks. The user can choose if they want to tweak in Blender (first render) or in Post. Probably a combination is good, i.e. initial tweaks in Blender with preview quality and then allow final tweaks in Post. ID/material-masks should be possible to render out quickly as needed during the post step (this is somewhat how Magoo, a "GI/raytracing" firm do it). Cheers!

**Comment by mifth** [comment]
Yes! It looks great! All we need - color and texture in the viewport.

**Comment by Lightye** [comment]
It is hard to wait for this. I have a feeling that if this is done well, all the way, it will be a knockout. WYSIWYG Man!

**Comment by Lightye** [comment]
Mifth, if no RenderMan Nodetree is attached the color of the Bxdf diffuse is already displayed in the viewport. However, when a nodetree is attached with for example PxrDisney the color of the viewport is not the same. If it would be copy that color value from somewhere lower down the pipe it would maybe be better? What about some average of the center of the Preview?

**Comment by bsavery** [comment]
Ahem, check out the latest github code from last night ;)

On Tue, Feb 2, 2016 at 11:02 AM, Lightye <notifications@github.com> wrote:

> Mifth, if no RenderMan Nodetree is attached the color of the Bxdf diffuse
> is already displayed in the viewport. However, when a nodetree is attached
> with for example PxrDisney the color of the viewport is not the same. If it
> would be copy that color value from somewhere lower down the pipe it would
> maybe be better? What about some average of the center of the Preview?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/124#issuecomment-178760004>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by Lightye** [comment]
That's sweet and even faster. Checked base color for the following and they are all connected to the openGL color (diffuse or specular). PxrConstant, PxrDiffuse, PxrDisney, PxrGlass (transmission), PxrLMDiffuse (front color), PxrLMGlass (Transmission), PxrLMMetal (specular), PxrLMPlastic (Diffuse), PxrMarschnerHair (Diffuse Color), PxrSkin (midColor), PxrVolume (Diffuse color). 

PxrLMSubsurface is excluded (maybe not necessary). 

That is well executed and neat. The interactive feedback here is fast and can be used for animating characters and doing previz.

**Comment by Lightye** [comment]
Guys, keep an eye on what happens when a mesh already have another shader assigned (for example from Cycles). It might block the correct color display until it is deleted.

**Comment by Lightye** [comment]
This simple visual feedback simplifies editing very much!

**Comment by Lightye** [comment]
Here's a bug/limitation: Changing a color from the Properties Editor works great, but not when doing it via the Node Editor. The color will change in the Node Editor and the Properties Editor, but not transfer to the 3D View (editor).

**Comment by mifth** [comment]
Hi.

I updated the code but there still no colors in the viewport. Did you add them? Or we still need to wait?
![selection_032](https://cloud.githubusercontent.com/assets/2251298/13048311/1c10d95c-d3f6-11e5-8b92-a77a804466c6.png)

**Comment by MWY3510** [comment]
mifth,

This feature is in the plugin. In order to see the color you do need to adjust the color option once just to make it show up.
Have a great day.

**Comment by bsavery** [comment]
ALso make sure your have material viewport shading turned on...

**Comment by bsavery** [comment]
Which it appears you do.

**Comment by MWY3510** [comment]
Well solid shading also works. It only shows the color though not any of
the lighting information. Just noting this, I am not disagreeing with
anything Brian said.

**Comment by bsavery** [comment]
Right.


On Mon, Feb 15, 2016 at 2:25 PM, MWY3510 <notifications@github.com> wrote:

> Well solid shading also works. It only shows the color though not any of
> the lighting information. Just noting this, I am not disagreeing with
> anything Brian said.
>
> On Mon, Feb 15, 2016 at 5:23 PM, bsavery <notifications@github.com> wrote:
>
> > Which it appears you do.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/bsavery/PRMan-for-Blender/issues/124#issuecomment-184421089
> >
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bsavery/PRMan-for-Blender/issues/124#issuecomment-184422578>
> .
>



-- 
brian.savery@gmail.com
508-274-8700

**Comment by mifth** [comment]
I udjusted all colors but nothing happened. I tried all material viewport too.
I'm on linux.

![selection_033](https://cloud.githubusercontent.com/assets/2251298/13071196/f5b092c2-d4a2-11e5-848f-dc76400656d6.png)

**Comment by mifth** [comment]
I opened log and found this http://pastebin.com/3h7x4U7M

**Comment by bsavery** [comment]
We should update this with 21 to match PxrSurface

**Comment by bsavery** [comment]
Closing.  I don't think we are going to fix this any better than it is now.
