### ISSUE TITLE
Two rib gen enhancement ideas:

### ISSUE THREAD

**Issue by bsavery** [bsavery/RenderManForBlender#244]
These would strictly be for optimizing rendering.  Won't make rib gen any easier really or harder.
1.  Output every data/particle/dupli block as a object master and then use instances for everything.  We kinda already do this but with Read archives 
2.  Test for objects on screen and use "immediatesubdivide" only on onscreen objects.

**Comment by bsavery** [comment]
One more.  Optimize get_mesh.  In create_mesh don't get the triangulated mesh.

**Comment by jdent02** [comment]
Wouldn't that be as simple as  changing calc_tessface=True to False?

**Comment by bsavery** [comment]
I think that's what I was hinting at
