### ISSUE TITLE
Turn on gpu noise for non-external rendering?  

### ISSUE THREAD

**Issue by bsavery** [bsavery/RenderManForBlender#383]
https://renderman.pixar.com/forum/showthread.php?s=&postid=194145#post194145

Worth investigating if what card is available matters, etc.

**Comment by jdent02** [comment]
Would it have anything to do with the denoise process being launched as a Python process?

I did try to get it work using the same '--override gpuIndex 0 --' command string as the external render but it always kicked out an error when rendering internally.

**Comment by jdent02** [comment]
I did not try modifying the filter .json file though

**Comment by bsavery** [comment]
I mean the RMANTREE variable is in the environment passed to the subprocess right?  

OH here's a thought.  Try adding shell=True to the subprocess call for the denoise.  Because cuda might need to write to the console

**Comment by bsavery** [comment]
Closed.
