### ISSUE TITLE
Alembic Animation is not actually working

### ISSUE THREAD

**Issue by enzyme69** [bsavery/RenderManForBlender#393]
By any chance did anyone experience Alembic Animation not to load? I render 180 and realizing the animation is static.

**Comment by jdent02** [comment]
We probably didn't add that modifier to the list of deforming ones. Will put in a fix


Sent from my iPhone

On Nov 20, 2016, at 10:01 PM, Jimmy Gunawan <notifications@github.com<mailto:notifications@github.com>> wrote:


By any chance did anyone experience Alembic Animation not to load? I render 180 and realizing the animation is static.

-

**Comment by enzyme69** [comment]
Thanks for checking, I will try using Blender in another computer, same Blend and Alembic animation. Maybe there is something funky going on.

I made a simpler animation using just Displace Modifier (deforming mesh), exported the ABC, and it works.

I will test again, one second.

**Comment by jdent02** [comment]
It was a simple fix.  There's a list of modifiers that are considered 'animating' by the exporter and we didn't add in the one for Alembic caches when those were added to Blender.

**Comment by enzyme69** [comment]
I copied the file from Mac to Windows and issue persists. The Alembic animation does not seem to run. So, my quick fix for now is to assign Expression so that the Override Frame of the modifier is equal to #frame

**Comment by enzyme69** [comment]
Seems like the alembic animation render sometimes works, sometimes doesn't.

If I am in the middle of animation, test render, and then run Render Animation (batch), it does not work.
If I jump to the very beginning and render, seems to work alright.

Testing again...

**Comment by jdent02** [comment]
A fix was put in for Alembic cache's so the exporter recognizes them as deforming modifiers.  Can you test again?

**Comment by bsavery** [comment]
Do we read alembic caches natively?  We can, I don't know how we would assign shaders though.

**Comment by jdent02** [comment]
No, I believe the Alembic caches are loaded into Blender and then exported like any other mesh.
