### ISSUE TITLE
More example on PxrVary... or PrimVar?

### ISSUE THREAD

**Issue by enzyme69** [bsavery/RenderManForBlender#433]
I wanted to know more about this PxrVary node.
https://renderman.pixar.com/resources/current/RenderMan/PxrVary.html

So far I understand I can use "Identifier Name" to quickly get randomization of Color value per Object basis.

What is the other option for and how to use use:custom attribute thing?

![screen shot 2017-01-11 at 10 43 30](https://cloud.githubusercontent.com/assets/3952687/21829566/eb152908-d7ea-11e6-900e-5a72cb6772a0.png)

Coloring per face with random is not possible, so what is the PrimVar for?

**Comment by enzyme69** [comment]
I wonder if PxrVary node that I really need or PrimVar node... but there is no documentation for Blender in regards to using PrimVar.

I am looking at Maya's example....
http://www.fundza.com/rfm/primvars_hypershade/index.html

**Comment by AndreasReschGFX** [comment]
I guess at this point the PrimVar and Attribute functionality isn't very well integrated in Blender. In Maya the options for attributes and PrimVars are a bit more flexible. Maybe something that will be addressed in the future. For now the "Identifier Name" is quite helpful though.

**Comment by jdent02** [comment]
They aren't thoroughly integrated, no.  The overall design approach of RfB is to make it easy for the hobbyist to use.  Most of them don't use advanced features like PrimVar's and Attributes so those areas tend to not be focused on unless someone (like you guys) specifically requests it.  Of course then someone has to find time to work on it.
