### ISSUE TITLE
Spool job problem

### ISSUE THREAD

**Issue by MarcoCheng** [bsavery/RenderManForBlender#448]
# Note: It is RM20.x version
(Because i cant run 20.x plug-in normally in 2.78, so i change addon folder name from PRMan-for-blender-20.x to PRMan-for-Blender-master)

When i Spool to local queue, a warning message is appear

Traceback (most recent call last):
  File "C:\Users\user\AppData\Roaming\Blender Foundation\Blender\2.78\scripts\addons\PRMan-for-Blender-master\operators.py", line 251, in execute
    aov_output = rpass.paths['aov_output']
KeyError: 'aov_output'

location: <unknown location>:-1

not sure what that is... since this file is quite large.. so what can i do to help debugging? May be rib file???

Thanks

**Comment by jdent02** [comment]
What is your AOV output path set to in the preferences?

**Comment by MarcoCheng** [comment]
output root: D:\Cache\Renderman/{blend}
AOV path: $OUT\images\{scene}.{layer}.{pass}.####.{file_type}

**Comment by MarcoCheng** [comment]
any news?

**Comment by jdent02** [comment]
I made some changes to the AOV code recently.  Can you try this one again?

**Comment by MarcoCheng** [comment]
Cant see any updated in 20.x ...
