### ISSUE TITLE
PRMan hair color based on texture, v2

### ISSUE THREAD

**Issue by lyonelDahu** [bsavery/RenderManForBlender#456]
Hi there,

I'm doing some heavy fur in blender, and I'm having a lot of trouble with it. The first thing I'm experiencing is about using a texture to color my fur. I did exactly what you said in that post here : https://github.com/bsavery/PRMan-for-Blender/issues/126#event-411558266 , and it's working for simple uvs. But when I'm trying to do the same thing with udims, it's unfortunately not working anymore... I feel like the export Emitter UV is only exporting the uvs between 0 and 1, or something like that :).

Do you have any suggestion ? I feel that I tried everything, with no luck. Thank you very much for any help !

Lyonel

**Comment by bsavery** [comment]
You would have to use the __MAPID__ in the texture name.  Did you try that?

**Comment by lyonelDahu** [comment]
Yes, I actually did that too. The textures are working well on my mesh, but when I use them for the fur, they are not rendered anymore. If I use a simple texture (no UDIM) for the fur (just to check), it's fine, but as soon as I use the MAPID in the texture name, it deseapear. 
I'll try to make a simple test scene for you as soon as I've got time.

**Comment by bsavery** [comment]
CLosed, unless you have an example to reopen?
