### ISSUE TITLE
Blender crash when making changes IPR

### ISSUE THREAD

**Issue by nielsmedemblik** [bsavery/RenderManForBlender#459]
When I enable lobes on the pxrSurface shader and change settings while IPR is active, blender gets stuck and after closing It blender crashes. The console says: 

![error](https://cloud.githubusercontent.com/assets/23041346/23704628/24c8cadc-0406-11e7-8fa3-26496ee90a43.jpg)

Anyone any idea?

Win10
Blender 2.78b
Prman 21.3

**Comment by bsavery** [comment]
Hmmm, not sure.  Any other clues?

Does PxrSurface work otherwise?
Brian
