### ISSUE TITLE
rgba render pass - blue and alpha channels swap

### ISSUE THREAD

**Issue by AlexPetrov108** [bsavery/RenderManForBlender#468]
Hi Brian, 

In rgba AOV pass blue and alpha channels are swapped, so you get solid white in blue channel and the blue data in alpha channel when render.

**Comment by jdent02** [comment]
I'll look into this one.

**Comment by bsavery** [comment]
probably just needs asrgba

**Comment by jdent02** [comment]
That should be added when AOV denoising isn't used.......

I'll check it anyway....

**Comment by jdent02** [comment]
Okay I can confirm that something wacky is going on with IT display and the 'rgba' AOV output.  The 'int asrgba' is set to 1 in the RIB and the channel output is "Ci,a" but like the error says the blue and alpha channels are swapped.  I ran an EXR of the same pass through EXRinfo and got the following:


C:\tmp\renderman_for_blender\tester_base\images>exrinfo Scene.RenderLayer.rgba.0001.exr

Scene.RenderLayer.rgba.0001.exr:

file format version: 2, flags 0x0
capDate (type string): "2017:04:05 20:46:25"
channels (type chlist):
    Ci.b, 32-bit floating-point, sampling 1 1
    Ci.g, 32-bit floating-point, sampling 1 1
    Ci.r, 32-bit floating-point, sampling 1 1
    Ci.~w, 32-bit floating-point, sampling 1 1
    a, 32-bit floating-point, sampling 1 1
    a.~w, 32-bit floating-point, sampling 1 1
checkpoint (type int): 7
checksum (type string): "0000000000000000"
clipFar (type float): 100
clipNear (type float): 0.1
comments (type string): "Created using: Pixar PhotoRealistic RenderMan 21.3
Created on: Jon-Laptop"
compression (type compression): zip, individual scanlines
dataWindow (type box2i): (0 0) - (959 539)
displayWindow (type box2i): (0 0) - (959 539)
lineOrder (type lineOrder): increasing y
pixelAspectRatio (type float): 1
screenWindowCenter (type v2f): (-7.00355e-007 -1.19209e-007)
screenWindowWidth (type float): 0.914285
type (type string): "scanlineimage"
utcOffset (type float): 21600
worldToCamera (type m44f):
   (0.687438 -0.296963 -0.662753 0
    0.726162 0.294656 0.621182 0
    -0.0108156 0.90829 -0.418201 0
    -0.15498 -0.038579 16.302 1)
worldToNDC (type m44f):
   (1.50377 -1.15486 -0.663416 -0.662753
    1.58848 1.14589 0.621804 0.621182
    -0.0236591 3.53224 -0.41862 -0.418201
    -0.339019 -0.15003 16.2182 16.302)


Not sure what those two channels with the ~w are.........

**Comment by jdent02** [comment]
As a side note, is there a good reason why we're doing full 32 float exports for the color channels?  Seems like overkill.......
