### ISSUE TITLE
running IPR on kitchen scene will crash Blender when undoing change of material

### ISSUE THREAD

**Issue by Lightye** [bsavery/RenderManForBlender#469]
1. Opened original kitchen scene
2. Enable Only Render Selected
3. Start IPR
4. Changed the material on an object to another
5. Undo (CMD + z)
6. Blender crash

• Above is repeatable
• If Blender don't crash on first ctrl+z it crash on second

**Comment by bsavery** [comment]
I fixed a few ctrl z crashes with the latest updates to the addon.  Have you tried that?

**Comment by bsavery** [comment]
Just checking if this is an issue with the latest addon?

**Comment by Lightye** [comment]
Ok, changed material a couple of times and could undo those changes without a crash. That is an improvement. 

However, if an additional ctrl+z is done, which probably attempt to undo starting IPR, there will be a crash.

**Comment by bsavery** [comment]
Well.... hmmm I think there's a way to make an operator not add to the undo stack.  I'll look into that.  Otherwise... don't do that ;)

**Comment by bsavery** [comment]
Falls under the "way less bugs if people use the software the way you intended" realm ;)

**Comment by bsavery** [comment]
I can recreate this on OSX.  Are you on OSX now or something else?

**Comment by Lightye** [comment]
for now always doing changes on OSX

external render to CentOS7

Since I know undoing starting IPR create a crash I'll be careful with that. However, think artists are usually not careful.

**Comment by bsavery** [comment]
I still can't reproduce this on OSX.  

Start IPR (from top shelf) then hit cmd + z multiple times, no crash

**Comment by Lightye** [comment]
Current release 170428 will survive a couple ctrl+z at first, but not very long.

video
http://sawe.asuscomm.com/ws/RenderMan_for_Blender/beta_testing/170429_crash_on_some_ctrl-z.zip

**Comment by Lightye** [comment]
I guess this is much better now.
