### ISSUE TITLE
IPR infinite loop and Blender crash with Add RenderMan nodetree

### ISSUE THREAD

**Issue by Lightye** [bsavery/RenderManForBlender#470]
1. Open original kitchen scene
2. Only render selected
3. Select a mesh (for example a paper on the table)
4. Dimension 10%
5. Start IPR
6. The camera keeps rotating so ESC is pressed
7. Add RenderMan nodetree to material
8. RFB is stuck in a loop (see the IPR view) and Blender will crash if IPR is closed.

Above is repeatable

**Comment by Lightye** [comment]
Somewhat similar to https://github.com/bsavery/PRMan-for-Blender/issues/459

**Comment by jdent02** [comment]
Do you have something other than the default material assigned to the paper?  A problem I've noticed is that if you have multiple items with the same material and you make changes to that material, it will sequentially update all the instances of that material in IPR (it doesn't do all of them at once).  Being that the default kitchen scene has hundreds of meshes with the same material, that might be your problem.

**Comment by Lightye** [comment]
This same effect appear in another scene, but it is repeatable on the default kitchen scene. 

It is some kind of bug.

**Comment by bsavery** [comment]
Just to confirm, you have the latest master build of addon?

**Comment by Lightye** [comment]
It was a recent version when this appeared same day as error report 

don't think it existed in whatever previous version was there 

because have not seen that before although been doing the same things

can confirm this again after another update if it persists

**Comment by bsavery** [comment]
Sorry, are you seeing this NOW, or just previously?

**Comment by Lightye** [comment]
Will confirm when seen again.

**Comment by Lightye** [comment]
Have not seen this for a while so I guess the issue is gone.
