### ISSUE TITLE
Smooth shading won't render when adding displacement

### ISSUE THREAD

**Issue by boboalice** [bsavery/RenderManForBlender#472]
![disp](https://cloud.githubusercontent.com/assets/27031391/24830677/4484b0de-1c93-11e7-9043-7ed5ed3475e8.png)

Blend file:

http://s000.tinyupload.com/download.php?file_id=68144250438659682828&t=6814425043865968282844209

**Comment by Lightye** [comment]
Check your Shading and VIsibility. There was an override added for micropolygons on this object.

![skarmavbild 2017-04-12 kl 18 01 24](https://cloud.githubusercontent.com/assets/14073317/24967396/3aaa4c8a-1faa-11e7-9156-2086562a34f7.png)

Happy rendering!

**Comment by Lightye** [comment]
Hmm, on a second thought maybe you want to have smooth interpolation of edges using displacement but without the micropolygons. 

Yes, also noticed that smooth normals don't work when a displacement node is attached. Indeed, also see that when adding a displacement node the smooth normals are made hard. 

Additionally, attempted to add a displacement modifier that reads a texture, but see that the texture loader for that is not supported (if you compare with Cycles you see there is a file selector).

**Comment by bsavery** [comment]
I think this is a PRMan issue.  Fixed recently for subdivs:
https://rmanwiki.pixar.com/display/REN/RenderMan+21.1#RenderMan21.1-Miscellaneouschanges

**Comment by bsavery** [comment]
Closing as it's a PRMan issue, not the blender plugin.
