### ISSUE TITLE
crash 170429

### ISSUE THREAD

**Issue by Lightye** [bsavery/RenderManForBlender#491]
• OSX 10.10.5
• file: sws_shaders_170429.blend
Is there any secure place to upload files rather than keeping them open to the public?

/tmp/sws_shaders.crash.txt

# Blender 2.78 (sub 0), Commit date: 2016-10-24 12:20, Hash e8299c8
bpy.context.space_data.lock_camera = False  # Property
bpy.context.space_data.lock_camera = True  # Property
Texture generation took 00:00:00  # Info
RIB generation took 00:00:00  # Info
PRMan: R90007 {SEVERE}  DisplayWindow failed to send display data (System Error: Broken pipe)
   # Error
PRMan: R56005 {SEVERE}  Cannot find message with id R56005 (System Error: Broken pipe)
   # Error

PRMan: Done Rendering. (elapsed time: 00:00:06)  # Info
bpy.context.object.hide = True  # Property
bpy.context.space_data.context = 'MATERIAL'  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].Diffuse_ui_open = True  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableDiffuse = True  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].Diffuse_ui_open = False  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].Glow_ui_open = True  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = False  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = True  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = False  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = True  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = False  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = True  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = False  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = True  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].enableGlow = False  # Property
bpy.data.node_groups["Shader Nodetree"].nodes["PxrSurface"].Glow_ui_open = False  # Property

# backtrace
0   blender                             0x0000000100bf076a BLI_system_backtrace + 58
1   blender                             0x000000010015731a sig_handle_crash + 362
2   libsystem_platform.dylib            0x00007fff8c6e4f1a _sigtramp + 26
3   ???                                 0x000060800005e540 0x0 + 106102872466752

**Comment by Lightye** [comment]
After the above the scene custom properties are deleted (loosing all non default scene settings). Will see if a similar crash returns.

**Comment by bsavery** [comment]
You can securely send them to me directly on slack...
