### ISSUE TITLE
pattern read input on second

### ISSUE THREAD

**Issue by Lightye** [bsavery/RenderManForBlender#492]
video
http://sawe.asuscomm.com/ws/RenderMan_for_Blender/beta_testing/170429_pattern_read_input_on_second.zip

**Comment by bsavery** [comment]
Sorry, can you describe what the issue is here?

Brian

**Comment by Lightye** [comment]
When running IPR and performing changes to shaders using numerical input I see that the change is not sent to the render immediately. If I input the same data twice it will update the IPR view. The issue is still there and was noticed again when editing patterns.

**Comment by bsavery** [comment]
The short answer is that this is expected, because the renderer is still processing the first edit you don't see it right away.  Mainly the pxrdirt node is slow because it does it's own raytracing.
