### ISSUE TITLE
Multiple UV maps

### ISSUE THREAD

**Issue by jdbener** [bsavery/RenderManForBlender#495]
I have spent hours (20 minutes) scouring the vast reaches of the internet (using google) in an attempt to find a way to take advantage of Blender's multiple UV maps system (or ST maps?). Is it possible to use two different UV maps in the same shader? If so how?

**Comment by bsavery** [comment]
Actually you can, go to the primitive variables section in the mesh data, create any number of primitive variables, and set their source to be each uvtexture you want to use.  Then name each variable something and use that name in the primvar s/t field in the PxrManifold2D.

**Comment by Zaush** [comment]
I'm actually pretty interested in seeing this in action as well, because the implementation isn't immediately accessible. Would it be possible to do a short YouTube video on this, or provide an example blend file that utilizes multiple UV sets?

**Comment by bsavery** [comment]
I think the explanation is fairly clear. Which part didn't work for you?

**Comment by jdbener** [comment]
The explanation is fairly clear, It's just not something that can be found anywhere but here. Showing off in one of your tutorials how it works or adding an example blend file would be very much appreciated.

**Comment by bsavery** [comment]
Fair point. There's a set of example files that needs to be expanded (see the other repo under my name). Maybe those could be used as example files.

**Comment by Zaush** [comment]
I was able to figure it out easily enough, but demonstrating it in your youtube channel could help others that don't know about this feature.
