### ISSUE TITLE
Vertex colors with multiple materials

### ISSUE THREAD

**Issue by abpy** [bsavery/RenderManForBlender#501]
I have found that vertex colors do not work if the object has more than 1 material.

**Comment by jdent02** [comment]
Multi material objects actually get split at export time (Renderman can only have one bxdf per mesh).  That might be altering the vertex color layers

**Comment by bsavery** [comment]
Attaching a scene would really help for us lazy programmers to diagnose.

**Comment by bsavery** [comment]
Fixed in latest checkin.
