### ISSUE TITLE
Rendering animations - 

### ISSUE THREAD

**Issue by Blenderbugg** [bsavery/RenderManForBlender#502]
Having problems with internal rendering:
IPR on
Display = keep UI
Render to = Blender
Press "render animation" and the folder loads up with blank files. 

![frame0040](https://cloud.githubusercontent.com/assets/28837471/26282525/6c5ca870-3e56-11e7-9979-f74842b1b58f.jpg)

I am running Mac OX on a 2010 Mack Pro tower 32gig ram
Blender 2.78c and the latest Renderman and Blender addon.

If I turn the IPR off and render the animation, Get a file with an image but renderman quits after the first file and Blender progress bar hangs at 100%. 

![frame0040](https://cloud.githubusercontent.com/assets/28837471/26282534/a03c1518-3e56-11e7-8bbb-7019f4ec5c0c.jpg)

Any Ideas?

**Comment by Zaush** [comment]
For rendering animation, I would highly recommend turning on external rendering and using that system to sent it to the queue. This allows you to keep working even while rendering, and renderman will chew through the files depositing them where your plugin's out directory is specified.

**Comment by Blenderbugg** [comment]
Thanks for the help. I'm still having the above problem with the internal render, don't know if its a bug in me or the program? Any ideas? 

However, thank you so much for that little, but critical, piece of info on how to specify an output directory for external rendering. I've been stuck on that for a while. I'm just running an external render now - frekin fast! It would be nice to have a video on the rendering process.

**Comment by bsavery** [comment]
So if you have IPR started that might be the issue, or are you still seeing issues without IPR?

**Comment by Blenderbugg** [comment]
Thanks for the reply but,
No joy :(
Just tried leaving IPR off during render process.
Other settings as above, set to render 25 frames.
1 Press render animation
2 Outputs one good frame to output folder
3 After output Blender process bar hangs at 100% for around 20sec then finishes.
4 Wait for a while
5 Click anywhere on the interface 
6 Bender gives error - "renderman exited"

The problem seems to be either blender or renderman waiting for something before rendering the next frame. Ive tried rebooting my computer, re-installing renderman and addon, creating a new scene. I am wondering if anyone else is having the same issue?
Eric

**Comment by bsavery** [comment]
Yeah I'm not exactly seeing that.  Can you attach the scene?

Bria

**Comment by Blenderbugg** [comment]
Hi Bria - here is the blend file. :)

I wanted to give you my original scene bit its too big. I created this simple box animation with the same settings, tried it and had the same results.

[box test.blend.zip](https://github.com/bsavery/RenderManForBlender/files/1020641/box.test.blend.zip)

**Comment by bsavery** [comment]
I see what you're saying.  Haven't gotten time to narrow it down though.

**Comment by Blenderbugg** [comment]
Thanks for look at this, I was beginning to think it was just me. 

The joys of the development process!

Glad to be helping out, I will keep on testing, see what else I come up with. Renderman is such a fantastic engine, I will be glad when I can make it my go-too for rendering all my animations. Ive put some star-ship eye candy on you tube rendered in Blender internal and cycles, can't wait to do one in renderman!   Look up theoldmaneric on You tube if you are interested. 

PS - It would be really nice if Pixar would give this add-on a bit of a lift up the hill - hint, hint.

**Comment by Blenderbugg** [comment]
I would like to keep this thread open for a while, I'm doing some heavy animation tests in external, see what happens

**Comment by bsavery** [comment]
Actually don't know what you mean by giving the addon a lift up the hill.  FYI I work in the renderman group as my day job.  This is sort of a side project, at Pixar generously donates some of my time to help ;).  Of course the biggest incentive is if more Blender users bought RenderMan licenses....

**Comment by Zaush** [comment]
Regarding the issue of watching the external queue in progress, you can choose "Render To:" as "it" and watch the renders in the imaging tool.

**Comment by Blenderbugg** [comment]
Yes, ill have a go at "it". god I love the name It, not someones cousen is he?

I'm going to test a large external render today, around 1m verts and maybe 300 frames, medium quality with a full range of textures and denoise. Most of my animation scenes are around 15 to 20 sec, good for long fades and stuff. I'll post the results here - and if it works put the movie up on my youtube channel theoldmaneric.

**Comment by bsavery** [comment]
https://github.com/bsavery/RenderManForBlender/commit/6117e45b2360e6d93f0abd5f2bd7b3638f72a51e

**Comment by bsavery** [comment]
Fixed see change above
