### ISSUE TITLE
sky lamp wrong intensity

### ISSUE THREAD

**Issue by enzoroa** [bsavery/RenderManForBlender#506]
Render sky lamp intensity  is wrong

Render
![render incorrect](https://cloud.githubusercontent.com/assets/4196482/26535669/a120e2d6-43fd-11e7-9ba0-08204410267a.png)

change a little bit the intensity from IPR mode and get correct result
![ipr correct](https://cloud.githubusercontent.com/assets/4196482/26535734/07ba2818-43fe-11e7-87ab-96ca4b61e58c.png)

blend file:
https://mega.nz/#!2JEUSLIL!IuoBJm-hwfiBkIdoXOlC3rAht6qARheLOfGYdN6Df2o

**Comment by bsavery** [comment]
Thanks.  This appears to be a PRMan issue that's we'll get fixed in a future version (probably 21.5).

**Comment by bsavery** [comment]
Closed, as this is a PRMan issue.
