### ISSUE TITLE
Creating shortcut for "Start IPR" not possible?

### ISSUE THREAD

**Issue by blezek** [bsavery/RenderManForBlender#508]
IPR does not always update when I make changes in Blender and I toggle IPR on and off.  Would like to make a shortcut rather than click, but does not seem possible?  There is no "Add Shortcut" for the `Start IPR` button when right clicking (unlike `Render` for instance).

![blender](https://cloud.githubusercontent.com/assets/76340/26580291/10197888-44fd-11e7-97dc-1abd0ff7f6ae.png)

**Comment by bsavery** [comment]
That seems to be a blender issue.  Hmmm...
