### ISSUE TITLE
Issue with unregistering addon

### ISSUE THREAD

**Issue by jdent02** [bsavery/RenderManForBlender#511]
https://renderman.pixar.com/forum/showthread.php?s=&postid=207739#post207739

Seems to be an issue where disabling the addon doesn't fully unregister the updater ops, thereby causing errors if the user tries to re-enable it.

**Comment by jdent02** [comment]
Also looks like a preset class isn't getting unregistered either.

**Comment by bsavery** [comment]
fixed
