### ISSUE TITLE
Can't save a material to the preset library

### ISSUE THREAD

**Issue by Lightye** [bsavery/RenderManForBlender#513]
Can not save a material to the preset library

Have attempted
• write permission
• different places for "RenderManAssetLibrary"

Please see the attached image with the error report. 
![save_material_to_preset_error](https://user-images.githubusercontent.com/14073317/27005929-c4dc7408-4e28-11e7-9fae-ba472c8f919d.jpg)

**Comment by Lightye** [comment]
Also, I do have the latest addon version.

**Comment by Lightye** [comment]
So wierd. Have had issues with this for some time. Tried another Blender version 2.78 and then 2.78c. Suddeny it works.

**Comment by Lightye** [comment]
Ok, I see that simple networks will be saved but not complex ones.

**Comment by Lightye** [comment]
[gdd_a.blend.zip](https://github.com/bsavery/RenderManForBlender/files/1066095/gdd_a.blend.zip)

**Comment by Lightye** [comment]
[export_network_to_presets_issue.blend.zip](https://github.com/bsavery/RenderManForBlender/files/1066103/export_network_to_presets_issue.blend.zip)

**Comment by bsavery** [comment]
Fixed.  The issue was the float -> color connections.
