### ISSUE TITLE
Have to set values twice during IPR for update to happen

### ISSUE THREAD

**Issue by Lightye** [bsavery/RenderManForBlender#514]
When editing nodes numerically and running IPR the render will not update if the value is not set two times. The same goes for changing between inside/outside. 

See picture and file.

![skarmavbild 2017-06-10 kl 23 12 55](https://user-images.githubusercontent.com/14073317/27006373-ed825152-4e32-11e7-8f0f-deb6d5596e43.png)

[twice_input_for_IPR_update_issue.blend.zip](https://github.com/bsavery/RenderManForBlender/files/1066120/twice_input_for_IPR_update_issue.blend.zip)

**Comment by bsavery** [comment]
#492 seems to be duplicate no?
