### ISSUE TITLE
pxrImagePlaneFilter fails

### ISSUE THREAD

**Issue by Lightye** [bsavery/RenderManForBlender#515]
The scene renders before adding the pxrImagePlaneFilter under the scene samples filter. When attached the scene will not render. If an image, like a tex, tif, or png, is attached Blender crash when attempting to render. 

Errors:
/Applications/Blender/2.78c/Blender_278c.app/Contents/MacOS/blender
Read new prefs: /Users/ws/Library/Application Support/Blender/2.78/config/userpref.blend
found bundled python: /Applications/Blender/2.78c/Blender_278c.app/Contents/MacOS/../Resources/2.78/python
renderman_for_blender updater verbose is enabled
renderman_for_blender Updater: Read in json settings from file
A08003 {ERROR}   RIBParameterList: Unknown parameter identifier: ?
A00003 {WARNING} Invalid initialization state.
Writing: /tmp/blender.crash.txt
Segmentation fault: 11

**Comment by Lightye** [comment]
[ballguy_test_scene.blend.zip](https://github.com/bsavery/RenderManForBlender/files/1069314/ballguy_test_scene.blend.zip)

**Comment by jdent02** [comment]
Evil bugs.....

**Comment by bsavery** [comment]
fixed
